image: dunkinthedonut/node-chrome

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-staging:       # This job runs in the build stage, which runs first.
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: build
  artifacts:
    paths:
      - "dist/JDMBlog"
  script:
    - npm install
    - npm run build:staging

build-production:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  artifacts:
    paths:
      - "dist/JDMBlog"
  script:
    - npm install
    - npm run build:prod

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - npm install
    - npm run test:ci

deploy-production-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
  artifacts:
    paths:
      - "dist/JDMBlog"
  script:
    - mv dist/JDMBlog public/
    - firebase deploy --token=$FIREBASE_TOKEN
