image: dunkinthedonut/node-chrome

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-staging:       # This job runs in the build stage, which runs first.
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: build
  script:
    - npm install
    - npm run build:staging
    - echo $CI_COMMIT_BRANCH
#    - firebase hosting:channel:deploy ${CI_COMMIT_BRANCH} --token=${FIREBASE_TOKEN}

build-production:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  script:
    - npm install
    - npm run build:prod
    - firebase deploy --token=$FIREBASE_TOKEN

#unit-test-job:   # This job runs in the test stage.
#  stage: test    # It only starts when the job in the build stage completes successfully.
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#  script:
#    - npm install
#    - npm run test:ci
